spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/blueriver
  rabbitmq:
    host: "rabbit"

build:
  version: "0.0.0"

accounts:
  message: "Dev Accounts API"
  contactDetails:
    name: "Dev Name"
    email: "Dev@email.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
