spring:
  rabbitmq:
    host: "rabbit"

eureka:
  instance:
    hostname: eureka-server
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
