spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/blueriver

build:
  version: "0.0.0"

loans:
  message: "Prod Loans API"
  contactDetails:
    name: "Prod Name"
    email: "Prod@email.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
